title: 
logo: /images/Dr. Kindler.jpg
description: For professional inquiries, collaboration opportunities, or discussion of my work:
- Email: `urs.kindler@rub.de`
- [LinkedIn](www.linkedin.com/in/dr-urs-kindler-074437228)
- [ORCID](https://orcid.org/0000-0001-9676-6323)
#show_downloads: true
theme: jekyll-theme-minimal #https://pages.github.com/themes/
