title: Dr. Urs Kindler
logo: /images/Urs picture.jpg
description: [linkedin](www.linkedin.com/in/dr-urs-kindler-074437228)
#show_downloads: true
theme: jekyll-theme-minimal #https://pages.github.com/themes/
