title: Dr. Urs Kindler
logo: /images/Urs picture.jpg
description: www.linkedin.com/in/profile 
https://public.tableau.com/app/profile/urs.kindler/vizzes
#show_downloads: true
theme: jekyll-theme-minimal #https://pages.github.com/themes/
